/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/CheckinManagement': RouteRecordInfo<'/admin/CheckinManagement', '/admin/CheckinManagement', Record<never, never>, Record<never, never>>,
    '/admin/MeetingReview': RouteRecordInfo<'/admin/MeetingReview', '/admin/MeetingReview', Record<never, never>, Record<never, never>>,
    '/booking/BookRoom': RouteRecordInfo<'/booking/BookRoom', '/booking/BookRoom', Record<never, never>, Record<never, never>>,
    '/booking/MyBookings': RouteRecordInfo<'/booking/MyBookings', '/booking/MyBookings', Record<never, never>, Record<never, never>>,
    '/booking/QueryRoom': RouteRecordInfo<'/booking/QueryRoom', '/booking/QueryRoom', Record<never, never>, Record<never, never>>,
    '/FaceCheckin': RouteRecordInfo<'/FaceCheckin', '/FaceCheckin', Record<never, never>, Record<never, never>>,
  }
}
